import { getStrings } from "../../i18n/languages.js";

// Strings for the Login/Register screens, keyed by ISO language code.
// English is the fallback base (see getStrings).
export const AUTH_STRINGS = {
    en: {
        emailPh: "Enter email",
        passwordPh: "Enter password",
        show: "Show",
        hide: "Hide",
        login: "Login",
        invalidCreds: "Email or Password are incorrect",
        accountInactive: "Your account is not active. Please contact the administrator.",
        network: "Server communication error, please try again later",
        noAccount: "Don't have an account?",
        registerHere: "Register here",
        fullNamePh: "Enter full name",
        confirmPh: "Confirm password",
        agePh: "Enter age",
        register: "Register",
        registerFailed: "Registration failed",
        registerOk: "You have registered successfully. Please log in.",
        codePh: "Enter Code",
        send: "Send",
        invalidCode: "Invalid code",
        male: "Male",
        female: "Female",
        // --- Space Academy auth redesign ---
        loginTitle: "Welcome back!",
        loginSubtitle: "Sign in to continue",
        registerTitle: "Create your account",
        registerSubtitle: "Join MathGalaxy and start your journey",
        loginSideDesc: "Personalized lessons, real-time feedback, and progress tracking to help you reach your goals.",
        registerSideTitle: "Your path to math mastery",
        feat1Title: "Personalized learning",
        feat1Desc: "Lessons tailored to your level",
        feat2Title: "Track your progress",
        feat2Desc: "See how you improve over time",
        feat3Title: "Stay motivated",
        feat3Desc: "Earn badges and achieve goals",
        forgotPassword: "Forgot password?",
        clickToStart: "Click to start",
        forgotTitle: "Reset your password",
        forgotSubtitle: "Enter your email and we'll send you a reset code.",
        sendResetCode: "Send reset code",
        resetTitle: "Set a new password",
        resetSubtitle: "Enter the code we emailed you and choose a new password.",
        newPasswordLabel: "New password",
        resetSubmit: "Reset password",
        resetSentMsg: "If the email exists, a reset code was sent.",
        resetDoneMsg: "Password updated. Please log in.",
        emailLabel: "Email",
        passwordLabel: "Password",
        confirmLabel: "Confirm password",
        fullNameLabel: "Full name",
        ageLabel: "Age",
        genderLabel: "Gender",
        rememberMe: "Remember me",
        agePlaceholder: "Select age",
        haveAccount: "Already have an account?",
        loginHere: "Log in",
        tagline: "Adaptive learning that guides you",
        verifyTitle: "Verify your email",
        verifyDesc: "We sent a verification code to {email}",
        resendQuestion: "Didn't get a code?",
        resend: "Resend",
        resendIn: "Resend in {seconds}s",
        verify: "Verify code",
        backToLogin: "Back to login",
        codeValidFor: "Code valid for 10 minutes",
        copyright: "© 2025 MathGalaxy · All rights reserved",
        ageGroupKids: "Kids",
        ageGroupTeens: "Teens",
        ageGroupAdults: "Adults",
        ageGroupOlder: "26+",
    },
    he: {
        emailPh: "הכניסו אימייל",
        passwordPh: "הכניסו סיסמה",
        show: "הצג",
        hide: "הסתר",
        login: "התחברות",
        invalidCreds: "אימייל או סיסמה שגויים",
        accountInactive: "החשבון אינו פעיל. פנה למנהל המערכת.",
        network: "שגיאת תקשורת עם השרת, אנא נסו שוב מאוחר יותר",
        noAccount: "אין לך משתמש?",
        registerHere: "הירשם כאן",
        fullNamePh: "הכניסו שם מלא",
        confirmPh: "אימות סיסמה",
        agePh: "הכניסו גיל",
        register: "הרשמה",
        registerFailed: "ההרשמה נכשלה",
        registerOk: "נרשמת בהצלחה. אנא התחבר/י.",
        codePh: "הכניסו קוד",
        send: "שליחה",
        invalidCode: "קוד שגוי",
        male: "זכר",
        female: "נקבה",
        // --- Space Academy auth redesign ---
        loginTitle: "ברוך שובך!",
        loginSubtitle: "התחבר כדי להמשיך",
        registerTitle: "צור את החשבון שלך",
        registerSubtitle: "הצטרף ל-MathGalaxy והתחל את המסע שלך",
        loginSideDesc: "שיעורים מותאמים אישית, משוב בזמן אמת ומעקב התקדמות שיעזרו לך להגיע ליעדים שלך.",
        registerSideTitle: "הדרך שלך למצוינות במתמטיקה",
        feat1Title: "למידה מותאמת אישית",
        feat1Desc: "שיעורים בהתאמה לרמה שלך",
        feat2Title: "מעקב אחר ההתקדמות",
        feat2Desc: "ראו כיצד אתם משתפרים לאורך זמן",
        feat3Title: "נשארים עם מוטיבציה",
        feat3Desc: "צוברים תגים ומשיגים יעדים",
        forgotPassword: "שכחת סיסמה?",
        clickToStart: "לחץ כדי להתחיל",
        forgotTitle: "איפוס סיסמה",
        forgotSubtitle: "הזן את האימייל ונשלח לך קוד איפוס.",
        sendResetCode: "שלח קוד איפוס",
        resetTitle: "בחר סיסמה חדשה",
        resetSubtitle: "הזן את הקוד שנשלח למייל ובחר סיסמה חדשה.",
        newPasswordLabel: "סיסמה חדשה",
        resetSubmit: "אפס סיסמה",
        resetSentMsg: "אם האימייל קיים, נשלח קוד איפוס.",
        resetDoneMsg: "הסיסמה עודכנה. אנא התחבר/י.",
        emailLabel: "אימייל",
        passwordLabel: "סיסמה",
        confirmLabel: "אימות סיסמה",
        fullNameLabel: "שם מלא",
        ageLabel: "גיל",
        genderLabel: "מין",
        rememberMe: "זכור אותי",
        agePlaceholder: "בחר גיל",
        haveAccount: "יש לך כבר חשבון?",
        loginHere: "התחבר",
        tagline: "למידה אדפטיבית שמובילה אותך",
        verifyTitle: "אימות מייל",
        verifyDesc: "שלחנו קוד אימות לכתובת {email}",
        resendQuestion: "לא קיבלת קוד?",
        resend: "שלח שוב",
        resendIn: "שלח שוב בעוד {seconds} שנ׳",
        verify: "אמת קוד",
        backToLogin: "חזרה להתחברות",
        codeValidFor: "הקוד תקף ל-10 דקות",
        copyright: "© 2025 MathGalaxy · כל הזכויות שמורות",
        ageGroupKids: "ילדים",
        ageGroupTeens: "נוער",
        ageGroupAdults: "מבוגרים",
        ageGroupOlder: "26+",
    },
    ru: {
        emailPh: "Введите эл. почту",
        passwordPh: "Введите пароль",
        show: "Показать",
        hide: "Скрыть",
        login: "Вход",
        invalidCreds: "Неверная эл. почта или пароль",
        accountInactive: "Ваш аккаунт неактивен. Обратитесь к администратору.",
        network: "Ошибка связи с сервером, попробуйте позже",
        noAccount: "Нет аккаунта?",
        registerHere: "Зарегистрируйтесь",
        fullNamePh: "Введите полное имя",
        confirmPh: "Подтвердите пароль",
        agePh: "Введите возраст",
        register: "Регистрация",
        registerFailed: "Регистрация не удалась",
        registerOk: "Регистрация успешна. Войдите в систему.",
        codePh: "Введите код",
        send: "Отправить",
        invalidCode: "Неверный код",
        male: "Мужской",
        female: "Женский",
        // --- Space Academy auth redesign ---
        loginTitle: "С возвращением!",
        loginSubtitle: "Войдите, чтобы продолжить",
        registerTitle: "Создайте аккаунт",
        registerSubtitle: "Присоединяйтесь к MathGalaxy и начните путь",
        loginSideDesc: "Персональные уроки, обратная связь в реальном времени и отслеживание прогресса для достижения ваших целей.",
        registerSideTitle: "Ваш путь к мастерству в математике",
        feat1Title: "Персональное обучение",
        feat1Desc: "Уроки под ваш уровень",
        feat2Title: "Отслеживание прогресса",
        feat2Desc: "Следите за своим ростом",
        feat3Title: "Мотивация",
        feat3Desc: "Получайте значки и достигайте целей",
        forgotPassword: "Забыли пароль?",
        clickToStart: "Нажмите, чтобы начать",
        forgotTitle: "Сброс пароля",
        forgotSubtitle: "Введите эл. почту, и мы отправим код для сброса.",
        sendResetCode: "Отправить код",
        resetTitle: "Новый пароль",
        resetSubtitle: "Введите код из письма и выберите новый пароль.",
        newPasswordLabel: "Новый пароль",
        resetSubmit: "Сбросить пароль",
        resetSentMsg: "Если почта существует, код отправлен.",
        resetDoneMsg: "Пароль обновлён. Войдите.",
        emailLabel: "Эл. почта",
        passwordLabel: "Пароль",
        confirmLabel: "Подтвердите пароль",
        fullNameLabel: "Полное имя",
        ageLabel: "Возраст",
        genderLabel: "Пол",
        rememberMe: "Запомнить меня",
        agePlaceholder: "Выберите возраст",
        haveAccount: "Уже есть аккаунт?",
        loginHere: "Войти",
        tagline: "Адаптивное обучение, которое ведёт вас",
        verifyTitle: "Подтверждение почты",
        verifyDesc: "Мы отправили код подтверждения на {email}",
        resendQuestion: "Не получили код?",
        resend: "Отправить снова",
        resendIn: "Повтор через {seconds}с",
        verify: "Подтвердить",
        backToLogin: "Назад ко входу",
        codeValidFor: "Код действует 10 минут",
        copyright: "© 2025 MathGalaxy · Все права защищены",
        ageGroupKids: "Дети",
        ageGroupTeens: "Подростки",
        ageGroupAdults: "Взрослые",
        ageGroupOlder: "26+",
    },
};

export const getAuthStrings = (language) => getStrings(AUTH_STRINGS, language);
