package com.adaptive.server.DTOs;

import com.adaptive.server.responses.QuestionResponse;

import java.util.List;

// Result of a successful battle start: the new star balance (after the 200 deduction), the
// resolved difficulty, the monster's HP for that level, the player's lives, and the batch of
// questions for the battle (generated by the existing rule-based generator).
public class StartBattleResponse {
    private int updatedStars;
    private int level;
    private int monsterMaxHp;
    private int playerLives;
    private List<QuestionResponse> questions;

    public StartBattleResponse() {
    }

    public StartBattleResponse(int updatedStars, int level, int monsterMaxHp,
                               int playerLives, List<QuestionResponse> questions) {
        this.updatedStars = updatedStars;
        this.level = level;
        this.monsterMaxHp = monsterMaxHp;
        this.playerLives = playerLives;
        this.questions = questions;
    }

    public int getUpdatedStars() { return updatedStars; }
    public void setUpdatedStars(int updatedStars) { this.updatedStars = updatedStars; }

    public int getLevel() { return level; }
    public void setLevel(int level) { this.level = level; }

    public int getMonsterMaxHp() { return monsterMaxHp; }
    public void setMonsterMaxHp(int monsterMaxHp) { this.monsterMaxHp = monsterMaxHp; }

    public int getPlayerLives() { return playerLives; }
    public void setPlayerLives(int playerLives) { this.playerLives = playerLives; }

    public List<QuestionResponse> getQuestions() { return questions; }
    public void setQuestions(List<QuestionResponse> questions) { this.questions = questions; }
}
