import { getStrings } from "../../i18n/languages.js";

// Strings for the student Games area + the Galaxy Battle game. English is the fallback base.
// Gendered entries are objects { male, female, neutral } — pick with the g() helper + user gender.
export const GAMES_STRINGS = {
    en: {
        gamesTitle: "Games",
        gamesSubtitle: "Spend your stars on a fun learning battle.",
        battleTitle: "Galaxy Battle",
        battleTagline: "Solve math to defeat the space monster!",
        playCost: "Costs {cost} ⭐",
        yourStars: "Your stars: {stars}",
        startGame: "Start battle",
        chooseTopic: "Choose a planet to battle",
        chooseTopicSub: "The monster's strength matches your level in that topic.",
        recommended: "Recommended ⚠️",
        yourLevel: "Your level: {level}",
        monsterEasy: "Easy monster",
        monsterMedium: "Medium monster",
        monsterHard: "Tough monster",
        you: { male: "You", female: "You", neutral: "You" },
        monsterOf: "{topic} monster",
        attackPrompt: "Solve to attack",
        combo: "Combo",
        shipLabel: "Your ship",
        battleStart: "Battle start!",
        fight: "FIGHT!",
        introHint: "Defeat the monster to earn a badge!",
        hurtToast: "Hit!",
        monsterChargeWarn: "⚠️ Monster attacks in {n}!",
        timeRunningOut: "Time's running out!",
        livesLabel: "Lives",
        streak: "Streak: {count}",
        superReady: "Super attack ready! 💥",
        superHit: "Super attack! 💥",
        notEnoughTitle: "Not enough stars",
        notEnoughBody: { male: "You don't have enough stars. Answer more questions to earn stars.",
                         female: "You don't have enough stars. Answer more questions to earn stars.",
                         neutral: "You don't have enough stars. Answer more questions to earn stars." },
        goPractice: "Go practice",
        close: "Close",
        winTitle: "You won! 🎉",
        winSub: "You defeated the monster!",
        winBadge: "🏆 Badge: Galaxy Champion",
        loseTitle: "Game over",
        loseSub: { male: "Try again after a bit more practice.", female: "Try again after a bit more practice.",
                   neutral: "Try again after a bit more practice." },
        backToGames: "Back to games",
        anotherBattle: "Another battle",
        backHome: "Back home",
        practiceTopic: "Practice this topic",
        loading: "Loading…",
        noBattleTopics: "No topics are available for battle right now.",
        errorStart: "Could not start the battle.",
        mainGame: "Main game",
        enemyLabel: "Enemy monster",
        previewQuestion: "What's the right answer?",
        choose: { male: "Choose", female: "Choose", neutral: "Choose" },
        continueToBattle: "Continue to battle",
        stepOf: "Step {n} of {total}",
        recommendedHelper: "The recommended planet matches your current level and helps you progress best.",
        resultTopic: "Battle topic",
        resultStreak: "Current streak",
        resultHearts: "Hearts left",
        winTitleAlt: "Well done! Battle complete",
        tipPlay: "Learn. Play. Win. Progress.",
        tipStars: "Every star brings you closer to success!",
        hintDark: "Dark mode is one click away 🌙",
        hintLight: "Light mode is one click away ☀️",
    },
    he: {
        gamesTitle: "משחקים",
        gamesSubtitle: "השקיעו כוכבים בקרב למידה כיפי.",
        battleTitle: "קרב גלקטי",
        battleTagline: "פתרו מתמטיקה כדי להביס את מפלצת החלל!",
        playCost: "עלות: {cost} ⭐",
        yourStars: "הכוכבים שלך: {stars}",
        startGame: "התחילו קרב",
        chooseTopic: "בחרו כוכב לקרב",
        chooseTopicSub: "עוצמת המפלצת מתאימה לרמה שלך בנושא.",
        recommended: "מומלץ עבורך ⚠️",
        yourLevel: "הרמה שלך: {level}",
        monsterEasy: "מפלצת קלה",
        monsterMedium: "מפלצת בינונית",
        monsterHard: "מפלצת חזקה",
        you: { male: "אתה", female: "את", neutral: "את/ה" },
        monsterOf: "מפלצת {topic}",
        attackPrompt: "פתרו כדי לתקוף",
        combo: "קומבו",
        shipLabel: "החללית שלך",
        battleStart: "הקרב מתחיל!",
        fight: "לקרב!",
        introHint: "הביסו את המפלצת כדי לזכות בתג!",
        hurtToast: "נפגעת!",
        monsterChargeWarn: "⚠️ המפלצת תוקפת בעוד {n}!",
        timeRunningOut: "הזמן אוזל!",
        livesLabel: "חיים",
        streak: "רצף: {count}",
        superReady: "מתקפת על מוכנה! 💥",
        superHit: "מתקפת על! 💥",
        notEnoughTitle: "אין מספיק כוכבים",
        notEnoughBody: { male: "אין לך מספיק כוכבים. ענה על עוד שאלות כדי לצבור כוכבים.",
                         female: "אין לך מספיק כוכבים. עני על עוד שאלות כדי לצבור כוכבים.",
                         neutral: "אין לך מספיק כוכבים. ענו על עוד שאלות כדי לצבור כוכבים." },
        goPractice: "לתרגול",
        close: "סגור",
        winTitle: "ניצחת! 🎉",
        winSub: "הבסת את המפלצת!",
        winBadge: "🏆 באדג': אלוף הגלקסיה",
        loseTitle: "הקרב הסתיים",
        loseSub: { male: "נסה שוב אחרי עוד קצת תרגול.", female: "נסי שוב אחרי עוד קצת תרגול.",
                   neutral: "נסו שוב אחרי עוד קצת תרגול." },
        backToGames: "חזרה למשחקים",
        anotherBattle: "קרב נוסף",
        backHome: "חזרה לבית",
        practiceTopic: "תרגול בנושא הזה",
        loading: "טוען…",
        noBattleTopics: "אין כרגע נושאים זמינים לקרב.",
        errorStart: "לא ניתן להתחיל את הקרב.",
        mainGame: "משחק ראשי",
        enemyLabel: "מפלצת האויב",
        previewQuestion: "מהי התשובה הנכונה?",
        choose: { male: "בחר", female: "בחרי", neutral: "בחירה" },
        continueToBattle: "המשיכו לקרב",
        stepOf: "שלב {n} מתוך {total}",
        recommendedHelper: "הכוכב המומלץ עבורך מתאים לרמתך הנוכחית ויעזור לך להתקדם בצורה הטובה ביותר.",
        resultTopic: "נושא הקרב",
        resultStreak: "רצף נוכחי",
        resultHearts: "לבבות שנשארו",
        winTitleAlt: "כל הכבוד! הקרב הושלם",
        tipPlay: "למדו. שחקו. נצחו. התקדמו.",
        tipStars: "כל כוכב מקרב אתכם להצלחה!",
        hintDark: "מצב כהה זמין בלחיצה אחת 🌙",
        hintLight: "מצב יום זמין בלחיצה אחת ☀️",
    },
    ru: {
        gamesTitle: "Игры",
        gamesSubtitle: "Потратьте звёзды на весёлую обучающую битву.",
        battleTitle: "Галактическая битва",
        battleTagline: "Решайте математику, чтобы победить монстра!",
        playCost: "Стоит {cost} ⭐",
        yourStars: "Ваши звёзды: {stars}",
        startGame: "Начать битву",
        chooseTopic: "Выберите планету для битвы",
        chooseTopicSub: "Сила монстра соответствует вашему уровню в теме.",
        recommended: "Рекомендуется ⚠️",
        yourLevel: "Ваш уровень: {level}",
        monsterEasy: "Лёгкий монстр",
        monsterMedium: "Средний монстр",
        monsterHard: "Сильный монстр",
        you: { male: "Вы", female: "Вы", neutral: "Вы" },
        monsterOf: "Монстр: {topic}",
        attackPrompt: "Решите, чтобы атаковать",
        combo: "Комбо",
        shipLabel: "Ваш корабль",
        battleStart: "Битва начинается!",
        fight: "В БОЙ!",
        introHint: "Победите монстра, чтобы получить значок!",
        hurtToast: "Удар!",
        monsterChargeWarn: "⚠️ Монстр атакует через {n}!",
        timeRunningOut: "Время на исходе!",
        livesLabel: "Жизни",
        streak: "Серия: {count}",
        superReady: "Супер-атака готова! 💥",
        superHit: "Супер-атака! 💥",
        notEnoughTitle: "Недостаточно звёзд",
        notEnoughBody: { male: "У вас недостаточно звёзд. Решайте больше задач, чтобы заработать звёзды.",
                         female: "У вас недостаточно звёзд. Решайте больше задач, чтобы заработать звёзды.",
                         neutral: "У вас недостаточно звёзд. Решайте больше задач, чтобы заработать звёзды." },
        goPractice: "К практике",
        close: "Закрыть",
        winTitle: "Победа! 🎉",
        winSub: "Вы победили монстра!",
        winBadge: "🏆 Значок: Чемпион галактики",
        loseTitle: "Игра окончена",
        loseSub: { male: "Попробуйте снова после практики.", female: "Попробуйте снова после практики.",
                   neutral: "Попробуйте снова после практики." },
        backToGames: "К играм",
        anotherBattle: "Ещё битва",
        backHome: "Домой",
        practiceTopic: "Практиковать эту тему",
        loading: "Загрузка…",
        noBattleTopics: "Сейчас нет доступных тем для битвы.",
        errorStart: "Не удалось начать битву.",
        mainGame: "Главная игра",
        enemyLabel: "Монстр-враг",
        previewQuestion: "Какой верный ответ?",
        choose: { male: "Выбрать", female: "Выбрать", neutral: "Выбрать" },
        continueToBattle: "В бой",
        stepOf: "Шаг {n} из {total}",
        recommendedHelper: "Рекомендованная планета соответствует вашему уровню и поможет продвигаться лучше всего.",
        resultTopic: "Тема битвы",
        resultStreak: "Текущая серия",
        resultHearts: "Осталось жизней",
        winTitleAlt: "Молодец! Битва завершена",
        tipPlay: "Учись. Играй. Побеждай. Расти.",
        tipStars: "Каждая звезда приближает к успеху!",
        hintDark: "Тёмный режим в один клик 🌙",
        hintLight: "Светлый режим в один клик ☀️",
    },
};

export const getGamesStrings = (language) => getStrings(GAMES_STRINGS, language);
