import { createAvatar } from '@dicebear/core';
import { avataaars } from '@dicebear/collection';

// Central avatar catalog (the ONLY place avatars are defined on the client). Images are
// generated by DiceBear (avataaars) from a FIXED unique seed per avatar — professional,
// deterministic illustrations that never change between loads and are never broken images.
// The SERVER owns the authoritative prices + ownership + star deduction; keep ids + prices
// in sync with server/.../service/AvatarCatalog.java.
//
// Each entry: { id, name(via nameKey), image, seed, style, gender, price, rarity, isFree }.
// `gender` (not the name) drives the store's gender tabs.

// Mature, professional looks: gender-appropriate hair, grown-up clothing, glasses/beard
// where it suits — so avatars read like real profile pictures, not cartoons.
const TOPS = {
    female: ['bob', 'bun', 'curvy', 'longButNotTooLong', 'miaWallace', 'straight01', 'straight02', 'straightAndStrand', 'bigHair'],
    male: ['shortFlat', 'shortRound', 'shortWaved', 'theCaesar', 'theCaesarAndSidePart', 'sides', 'shaggy'],
    neutral: ['shortCurly', 'shortFlat', 'sides', 'curly', 'dreads01'],
};
const CLOTHING = ['blazerAndShirt', 'blazerAndSweater', 'collarAndSweater', 'shirtCrewNeck', 'hoodie'];
const GLASSES = ['prescription01', 'prescription02', 'round', 'wayfarers'];

// Pleasant, grown-up expressions only — avataaars' random mouths/eyes (scream, cry,
// tongue, dizzy…) are what make it look goofy, so we constrain to a calm, friendly set.
const MOUTH = ['default', 'smile', 'serious', 'twinkle'];
const EYES = ['default', 'happy', 'wink', 'squint', 'side'];
const EYEBROWS = ['default', 'defaultNatural', 'flatNatural', 'raisedExcited'];

const makeImage = (seed, gender, bg, glasses) => createAvatar(avataaars, {
    seed,
    radius: 50,
    size: 140,
    backgroundColor: bg,
    backgroundType: ['gradientLinear'],
    top: TOPS[gender],
    clothing: CLOTHING,
    mouth: MOUTH,
    eyes: EYES,
    eyebrows: EYEBROWS,
    facialHairProbability: gender === 'male' ? 45 : 0,
    accessories: glasses ? GLASSES : [],
    accessoriesProbability: glasses ? 100 : 0,
}).toDataUri();

// id, nameKey, gender, price, rarity, pictureId, seed, bg gradient, glasses?
const DEFS = [
    // free starters (one per tab; two map to a saved pictureId slot)
    { id: 'a-researcher-f',  nameKey: 'avResearcher',  gender: 'female',  price: 0,   rarity: 'basic',     pictureId: 1,    seed: 'galaxy-researcher-female-01', bg: ['cbb6ff', '7c4dff'] },
    { id: 'a-explorer-m',    nameKey: 'avExplorerM',   gender: 'male',    price: 0,   rarity: 'basic',     pictureId: 0,    seed: 'space-explorer-male-01',      bg: ['a7c7ff', '3f6fd6'] },
    { id: 'a-discoverer-n',  nameKey: 'avDiscoverer',  gender: 'neutral', price: 0,   rarity: 'basic',     pictureId: null, seed: 'star-discoverer-neutral-01',  bg: ['9be0d0', '1fae9a'] },
    // rare (80–120)
    { id: 'a-engineer-f',    nameKey: 'avEngineerF',   gender: 'female',  price: 80,  rarity: 'rare',      pictureId: null, seed: 'space-engineer-female-01',    bg: ['ffc1e3', 'e3589b'] },
    { id: 'a-engineer-m',    nameKey: 'avEngineerM',   gender: 'male',    price: 80,  rarity: 'rare',      pictureId: null, seed: 'galactic-engineer-male-01',   bg: ['bdebc0', '2f9e6a'] },
    { id: 'a-theorist-n',    nameKey: 'avTheorist',    gender: 'neutral', price: 120, rarity: 'rare',      pictureId: null, seed: 'theory-researcher-neutral-01', bg: ['aab4d4', '5b6bdd'], glasses: true },
    // epic (150–250)
    { id: 'a-astronomer-f',  nameKey: 'avAstronomer',  gender: 'female',  price: 150, rarity: 'epic',      pictureId: null, seed: 'astronomer-female-01',        bg: ['c7b6ff', '6a3fd6'], glasses: true },
    { id: 'a-captain-m',     nameKey: 'avCaptain',     gender: 'male',    price: 150, rarity: 'epic',      pictureId: null, seed: 'cosmic-captain-male-01',      bg: ['9fb8ff', '3f5fd6'] },
    { id: 'a-pioneer-n',     nameKey: 'avPioneer',     gender: 'neutral', price: 200, rarity: 'epic',      pictureId: null, seed: 'cosmic-pioneer-neutral-01',   bg: ['ffd6a6', 'f59e0b'] },
    { id: 'a-scientist-f',   nameKey: 'avScientist',   gender: 'female',  price: 250, rarity: 'epic',      pictureId: null, seed: 'future-scientist-female-01',  bg: ['e0b3ff', '9b4dff'], glasses: true },
    { id: 'a-mathematician-m', nameKey: 'avMathematician', gender: 'male', price: 250, rarity: 'epic',     pictureId: null, seed: 'galactic-mathematician-male-01', bg: ['b8a6ff', '5e3fc0'] },
    // legendary (300+)
    { id: 'a-superstar-n',   nameKey: 'avSuperstar',   gender: 'neutral', price: 300, rarity: 'legendary', pictureId: null, seed: 'cosmic-superstar-neutral-01',  bg: ['ffd86b', 'ff7eb3'], glasses: true },
];

export const AVATAR_CATALOG = DEFS.map((d) => ({
    id: d.id,
    nameKey: d.nameKey,
    gender: d.gender,
    price: d.price,
    rarity: d.rarity,
    isFree: d.price === 0,
    pictureId: d.pictureId,
    seed: d.seed,
    style: 'avataaars',
    image: makeImage(d.seed, d.gender, d.bg, d.glasses),
}));

export const findAvatar = (id) => AVATAR_CATALOG.find(a => a.id === id) || null;

// The catalog id that corresponds to a saved profile pictureId (real-slot avatars only).
export const idForPictureId = (pictureId) => AVATAR_CATALOG.find(a => a.pictureId === pictureId)?.id || 'a-researcher-f';

// Default avatar for a student who hasn't chosen one — picked by gender.
export const defaultAvatarFor = (gender) =>
    findAvatar(gender === 'male' ? 'a-explorer-m' : gender === 'female' ? 'a-researcher-f' : 'a-discoverer-n');

// Resolve the avatar to show for a student anywhere (profile, leaderboard): their explicit
// choice, else the legacy pictureId slot, else a gender default. Single source of truth.
export const resolveAvatar = ({ selectedAvatarId, pictureId, gender } = {}) =>
    (selectedAvatarId && findAvatar(selectedAvatarId))
    || (pictureId != null && findAvatar(idForPictureId(pictureId)))
    || defaultAvatarFor(gender);
