import { getStrings } from "../../i18n/languages.js";

// Strings for the Profile / Settings page, the edit modal and the avatar store.
// English is the fallback base (see getStrings). Gender-dependent keys are
// { male, female, neutral } objects, picked via a safe g() helper in the component.
// Theme/language option *labels* come from the backend and are rendered as-is.
export const PROFILE_SETTINGS_STRINGS = {
    en: {
        pleaseLogIn: "Please log in to view your profile.",
        title: "Profile settings",
        subtitle: "Manage your profile and preferences",
        loading: "Loading…",
        loadError: "Could not load your profile. Please refresh the page.",
        saveSuccess: "Profile updated successfully!",
        saveFailed: "Could not save. Please try again.",
        notSet: "Not set",
        // profile card
        editProfile: "Edit profile",
        chooseAvatarBtn: "Choose avatar",
        levelBadge: "Level {level}",
        gradeBadge: "Class",
        starsBadge: "{stars} stars",
        // setting cards
        sectionAvatar: "My avatar",
        avatarCurrent: "Current avatar",
        changeAvatar: "Change avatar",
        theme: "Theme",
        language: "Language",
        sectionAccessibility: "Accessibility",
        a11yHint: "Adapt the interface to your needs",
        a11yTextSize: "Text size",
        a11yTextSmall: "Small text",
        a11yTextNormal: "Normal text",
        a11yTextLarge: "Large text",
        a11yContrast: "High contrast",
        a11yMotion: "Reduce animations",
        a11yFont: "Readable font (dyslexia)",
        sectionNotifications: "Notifications",
        notificationsHint: "Get important updates",
        notificationsHistory: "Messages from the last 7 days",
        notificationsEmpty: "No messages in the last 7 days",
        notificationsLoading: "Loading notifications…",
        sectionStars: "My stars",
        starsHint: "Keep learning and earning stars!",
        sectionMyAvatars: "My avatars",
        viewAll: "View all",
        viewCollection: { male: "View my collection", female: "View my collection", neutral: "My collection" },
        sectionLastAchievement: "Latest achievement",
        achievementName: "Rising star",
        achievementDesc: "Reached level {level}",
        // gender display
        genderLabel: "Gender",
        genderMale: "Boy", genderFemale: "Girl", genderNeutral: "—",
        // edit modal
        editTitle: "Edit profile",
        fieldName: "Full name",
        fieldEmail: "Email",
        fieldGender: "Gender",
        readonlyNote: "read-only",
        saving: "Saving…",
        saveChanges: "Save changes",
        cancel: "Cancel",
        // avatar store
        storeTitle: { male: "Choose your avatar", female: "Choose your avatar", neutral: "Choose your avatar" },
        starsAvailable: "My stars: {stars}",
        tabRecommended: "Recommended",
        tabGirls: "Girls",
        tabBoys: "Boys",
        tabAll: "All avatars",
        tabMine: "My avatars",
        free: "Free",
        select: { male: "Select", female: "Select", neutral: "Select" },
        selected: "Selected",
        buy: { male: "Buy", female: "Buy", neutral: "Buy" },
        needStars: "{n} more stars needed",
        myAvatarsBtn: "My avatars",
        close: "Close",
        storeEmpty: "No avatars in this category yet.",
        boughtMsg: "Avatar unlocked! 🎉",
        // avatar display names
        avatarNames: {
            avResearcher: "Galaxy researcher", avExplorerM: "Space explorer", avDiscoverer: "Star discoverer",
            avEngineerF: "Space engineer", avEngineerM: "Galactic engineer", avTheorist: "Theory researcher",
            avAstronomer: "Astronomer", avCaptain: "Cosmic captain", avPioneer: "Cosmic pioneer",
            avScientist: "Future scientist", avMathematician: "Galactic mathematician", avSuperstar: "Superstar",
        },
        avatarAlt: "Your avatar",
    },
    he: {
        pleaseLogIn: "אנא התחברו כדי לצפות בפרופיל שלכם.",
        title: "הגדרות פרופיל",
        subtitle: "נהלו את הפרופיל וההעדפות שלכם",
        loading: "טוען…",
        loadError: "לא ניתן לטעון את הפרופיל שלך. אנא רעננו את הדף.",
        saveSuccess: "הפרופיל עודכן בהצלחה!",
        saveFailed: "לא ניתן לשמור. אנא נסו שוב.",
        notSet: "לא הוגדר",
        // profile card
        editProfile: "עריכת פרופיל",
        chooseAvatarBtn: "בחירת אווטאר",
        levelBadge: "רמה {level}",
        gradeBadge: "כיתה",
        starsBadge: "{stars} כוכבים",
        // setting cards
        sectionAvatar: "האווטאר שלי",
        avatarCurrent: "האווטאר הנוכחי",
        changeAvatar: "שינוי אווטאר",
        theme: "ערכת נושא",
        language: "שפה",
        sectionAccessibility: "נגישות",
        a11yHint: "התאימו את חוויית הלמידה לצרכים שלכם",
        a11yTextSize: "גודל טקסט",
        a11yTextSmall: "טקסט קטן",
        a11yTextNormal: "טקסט רגיל",
        a11yTextLarge: "טקסט גדול",
        a11yContrast: "ניגודיות גבוהה",
        a11yMotion: "הפחתת אנימציות",
        a11yFont: "פונט קריא (לדיסלקציה)",
        sectionNotifications: "התראות",
        notificationsHint: "קבלו עדכונים חשובים",
        notificationsHistory: "הודעות מ-7 הימים האחרונים",
        notificationsEmpty: "אין הודעות מ-7 הימים האחרונים",
        notificationsLoading: "טוען התראות…",
        sectionStars: "הכוכבים שלי",
        starsHint: "המשיכו ללמוד ולהרוויח כוכבים!",
        sectionMyAvatars: "האווטארים שלי",
        viewAll: "ראו את כולם",
        viewCollection: { male: "צפה באוסף שלי", female: "צפי באוסף שלי", neutral: "האוסף שלי" },
        sectionLastAchievement: "הישג אחרון",
        achievementName: "כוכב עולה",
        achievementDesc: "הגעת לרמה {level}",
        // gender display
        genderLabel: "מגדר",
        genderMale: "בן", genderFemale: "בת", genderNeutral: "—",
        // edit modal
        editTitle: "עריכת פרופיל",
        fieldName: "שם מלא",
        fieldEmail: "אימייל",
        fieldGender: "מגדר",
        readonlyNote: "לקריאה בלבד",
        saving: "שומר…",
        saveChanges: "שמירת שינויים",
        cancel: "ביטול",
        // avatar store
        storeTitle: { male: "בחר את האווטאר שלך", female: "בחרי את האווטאר שלך", neutral: "בחרו את האווטאר שלכם" },
        starsAvailable: "הכוכבים שלי: {stars}",
        tabRecommended: "מומלצים עבורך",
        tabGirls: "בנות",
        tabBoys: "בנים",
        tabAll: "כל האווטארים",
        tabMine: "האווטארים שלי",
        free: "חינם",
        select: { male: "בחר", female: "בחרי", neutral: "בחרו" },
        selected: "נבחר",
        buy: { male: "קנה", female: "קני", neutral: "קנו" },
        needStars: "חסרים לך {n} כוכבים",
        myAvatarsBtn: "האווטארים שלי",
        close: "סגור",
        storeEmpty: "אין עדיין אווטארים בקטגוריה זו.",
        boughtMsg: "האווטאר נפתח! 🎉",
        // avatar display names
        avatarNames: {
            avResearcher: "חוקרת גלקסיה", avExplorerM: "חוקר חלל", avDiscoverer: "מגלה כוכבים",
            avEngineerF: "מהנדסת חלל", avEngineerM: "מהנדס גלקטי", avTheorist: "חוקר תיאוריות",
            avAstronomer: "אסטרונומית", avCaptain: "קפטן קוסמי", avPioneer: "חלוץ קוסמי",
            avScientist: "מדענית עתיד", avMathematician: "מתמטיקאי גלקטי", avSuperstar: "כוכב על",
        },
        avatarAlt: "הדמות שלך",
    },
    ru: {
        pleaseLogIn: "Войдите, чтобы просмотреть свой профиль.",
        title: "Настройки профиля",
        subtitle: "Управляйте профилем и настройками",
        loading: "Загрузка…",
        loadError: "Не удалось загрузить профиль. Обновите страницу.",
        saveSuccess: "Профиль успешно обновлён!",
        saveFailed: "Не удалось сохранить. Попробуйте ещё раз.",
        notSet: "Не задано",
        // profile card
        editProfile: "Редактировать профиль",
        chooseAvatarBtn: "Выбрать аватар",
        levelBadge: "Уровень {level}",
        gradeBadge: "Класс",
        starsBadge: "{stars} звёзд",
        // setting cards
        sectionAvatar: "Мой аватар",
        avatarCurrent: "Текущий аватар",
        changeAvatar: "Сменить аватар",
        theme: "Тема",
        language: "Язык",
        sectionAccessibility: "Доступность",
        a11yHint: "Настройте интерфейс под себя",
        a11yTextSize: "Размер текста",
        a11yTextSmall: "Мелкий текст",
        a11yTextNormal: "Обычный текст",
        a11yTextLarge: "Крупный текст",
        a11yContrast: "Высокий контраст",
        a11yMotion: "Меньше анимаций",
        a11yFont: "Удобный шрифт (дислексия)",
        sectionNotifications: "Уведомления",
        notificationsHint: "Получайте важные обновления",
        notificationsHistory: "Сообщения за последние 7 дней",
        notificationsEmpty: "Нет сообщений за последние 7 дней",
        notificationsLoading: "Загрузка уведомлений…",
        sectionStars: "Мои звёзды",
        starsHint: "Продолжайте учиться и зарабатывать звёзды!",
        sectionMyAvatars: "Мои аватары",
        viewAll: "Показать все",
        viewCollection: { male: "Моя коллекция", female: "Моя коллекция", neutral: "Моя коллекция" },
        sectionLastAchievement: "Последнее достижение",
        achievementName: "Восходящая звезда",
        achievementDesc: "Достигнут уровень {level}",
        // gender display
        genderLabel: "Пол",
        genderMale: "Мальчик", genderFemale: "Девочка", genderNeutral: "—",
        // edit modal
        editTitle: "Редактировать профиль",
        fieldName: "Полное имя",
        fieldEmail: "Эл. почта",
        fieldGender: "Пол",
        readonlyNote: "только чтение",
        saving: "Сохранение…",
        saveChanges: "Сохранить изменения",
        cancel: "Отмена",
        // avatar store
        storeTitle: { male: "Выберите свой аватар", female: "Выберите свой аватар", neutral: "Выберите свой аватар" },
        starsAvailable: "Мои звёзды: {stars}",
        tabRecommended: "Рекомендуемые",
        tabGirls: "Девочки",
        tabBoys: "Мальчики",
        tabAll: "Все аватары",
        tabMine: "Мои аватары",
        free: "Бесплатно",
        select: { male: "Выбрать", female: "Выбрать", neutral: "Выбрать" },
        selected: "Выбран",
        buy: { male: "Купить", female: "Купить", neutral: "Купить" },
        needStars: "Не хватает {n} звёзд",
        myAvatarsBtn: "Мои аватары",
        close: "Закрыть",
        storeEmpty: "В этой категории пока нет аватаров.",
        boughtMsg: "Аватар разблокирован! 🎉",
        // avatar display names
        avatarNames: {
            avResearcher: "Исследовательница галактик", avExplorerM: "Космический исследователь", avDiscoverer: "Открыватель звёзд",
            avEngineerF: "Космический инженер", avEngineerM: "Галактический инженер", avTheorist: "Исследователь теорий",
            avAstronomer: "Астроном", avCaptain: "Космический капитан", avPioneer: "Космический первопроходец",
            avScientist: "Учёная будущего", avMathematician: "Галактический математик", avSuperstar: "Суперзвезда",
        },
        avatarAlt: "Ваш аватар",
    },
};

export const getProfileSettingsStrings = (language) => getStrings(PROFILE_SETTINGS_STRINGS, language);
