import { getStrings } from "../../i18n/languages.js";

// All Admin UI strings, keyed by ISO language code. English is the fallback base
// (see getStrings). Adding a language = adding one block here.
export const ADMIN_STRINGS = {
    en: {
        // shared
        loading: "Loading...",
        save: "Save",
        cancel: "Cancel",
        edit: "Edit",
        colId: "ID",
        colName: "Name",
        errGeneric: "The action failed.",
        // dashboard
        dashboardTitle: "Admin Dashboard",
        welcome: "Welcome",
        roleLabel: "role",
        dashboardNote: "Phase 0 — entry verification. Management modules will be built in later phases.",
        manageUsers: "Manage users →",
        manageTopics: "Manage topics →",
        // users
        usersTitle: "User Management",
        usersLoadError: "Failed to load the user list.",
        usersPageStatus: "Page {page} of {total} ({count} users)",
        prev: "← Previous",
        next: "Next →",
        colEmail: "Email",
        colRole: "Role",
        colAge: "Age",
        colGender: "Gender",
        colStars: "Stars",
        colCreated: "Created",
        // topics
        topicsTitle: "Topic Management",
        topicsHint: "A new topic is created as a draft and is not shown to students until published. A topic cannot be published without subjects.",
        newTopic: "New topic",
        editTopic: "Edit topic",
        topicsLoadError: "Failed to load topics.",
        colStatus: "Status",
        colSubjects: "Subjects",
        colActions: "Actions",
        statusActive: "Active",
        statusDraft: "Draft",
        publish: "Publish",
        disable: "Disable",
        cannotPublishEmpty: "A topic without subjects cannot be published.",
        topicNamePlaceholder: "Topic name",
        errDuplicateName: "Topic name already exists.",
        errNameRequired: "Topic name is required.",
    },
    he: {
        // shared
        loading: "טוען...",
        save: "שמירה",
        cancel: "ביטול",
        edit: "עריכה",
        colId: "ID",
        colName: "שם",
        errGeneric: "הפעולה נכשלה.",
        // dashboard
        dashboardTitle: "לוח ניהול",
        welcome: "ברוך הבא",
        roleLabel: "תפקיד",
        dashboardNote: "שלב 0 — אימות כניסה. מודולי הניהול ייבנו בשלבים הבאים.",
        manageUsers: "ניהול משתמשים →",
        manageTopics: "ניהול נושאים →",
        // users
        usersTitle: "ניהול משתמשים",
        usersLoadError: "לא הצלחתי לטעון את רשימת המשתמשים.",
        usersPageStatus: "עמוד {page} מתוך {total} ({count} משתמשים)",
        prev: "← הקודם",
        next: "הבא →",
        colEmail: "Email",
        colRole: "תפקיד",
        colAge: "גיל",
        colGender: "מגדר",
        colStars: "כוכבים",
        colCreated: "נוצר",
        // topics
        topicsTitle: "ניהול נושאים",
        topicsHint: "נושא חדש נוצר כטיוטה ואינו מוצג לתלמידים עד שמפרסמים אותו. אי אפשר לפרסם נושא בלי תתי-נושאים.",
        newTopic: "נושא חדש",
        editTopic: "עריכת נושא",
        topicsLoadError: "לא הצלחתי לטעון את הנושאים.",
        colStatus: "סטטוס",
        colSubjects: "תתי-נושאים",
        colActions: "פעולות",
        statusActive: "פעיל",
        statusDraft: "טיוטה",
        publish: "פרסם",
        disable: "השבת",
        cannotPublishEmpty: "אי אפשר לפרסם נושא בלי תתי-נושאים.",
        topicNamePlaceholder: "שם הנושא",
        errDuplicateName: "שם הנושא כבר קיים.",
        errNameRequired: "שם הנושא נדרש.",
    },
    ru: {
        // shared
        loading: "Загрузка...",
        save: "Сохранить",
        cancel: "Отмена",
        edit: "Редактировать",
        colId: "ID",
        colName: "Название",
        errGeneric: "Действие не удалось.",
        // dashboard
        dashboardTitle: "Панель администратора",
        welcome: "Добро пожаловать",
        roleLabel: "роль",
        dashboardNote: "Этап 0 — проверка входа. Модули управления будут добавлены позже.",
        manageUsers: "Управление пользователями →",
        manageTopics: "Управление темами →",
        // users
        usersTitle: "Управление пользователями",
        usersLoadError: "Не удалось загрузить список пользователей.",
        usersPageStatus: "Страница {page} из {total} ({count} пользователей)",
        prev: "← Назад",
        next: "Вперёд →",
        colEmail: "Эл. почта",
        colRole: "Роль",
        colAge: "Возраст",
        colGender: "Пол",
        colStars: "Звёзды",
        colCreated: "Создан",
        // topics
        topicsTitle: "Управление темами",
        topicsHint: "Новая тема создаётся как черновик и не показывается ученикам до публикации. Тему нельзя опубликовать без подтем.",
        newTopic: "Новая тема",
        editTopic: "Редактировать тему",
        topicsLoadError: "Не удалось загрузить темы.",
        colStatus: "Статус",
        colSubjects: "Подтемы",
        colActions: "Действия",
        statusActive: "Активна",
        statusDraft: "Черновик",
        publish: "Опубликовать",
        disable: "Отключить",
        cannotPublishEmpty: "Нельзя опубликовать тему без подтем.",
        topicNamePlaceholder: "Название темы",
        errDuplicateName: "Тема с таким названием уже существует.",
        errNameRequired: "Название темы обязательно.",
    },
};

export const getAdminStrings = (language) => getStrings(ADMIN_STRINGS, language);
