import { getStrings } from "../../i18n/languages.js";

// All Admin UI strings, keyed by ISO language code. English is the fallback base
// (see getStrings). Adding a language = adding one block here.
export const ADMIN_STRINGS = {
    en: {
        // shared
        loading: "Loading...",
        save: "Save",
        cancel: "Cancel",
        edit: "Edit",
        colId: "ID",
        colName: "Name",
        errGeneric: "The action failed.",
        // dashboard
        dashboardTitle: "Admin Dashboard",
        welcome: "Welcome",
        roleLabel: "role",
        dashboardNote: "Phase 0 — entry verification. Management modules will be built in later phases.",
        manageUsers: "Manage users →",
        manageTopics: "Manage topics →",
        // analytics
        cardUsers: "Users",
        cardStudents: "Students",
        cardAttempts: "Attempts",
        cardSuccessRate: "Success rate",
        cardActive7d: "Active learners (7d)",
        hardestTitle: "Learning areas needing attention",
        commonErrorsTitle: "Common errors",
        leaderboardTitle: "Top 10 students",
        colAttempts: "Attempts",
        colSuccessRate: "Success rate",
        colError: "Error pattern",
        colOccurrences: "Occurrences",
        analyticsLoadError: "Failed to load analytics.",
        noData: "No data yet.",
        // users
        usersTitle: "User Management",
        usersLoadError: "Failed to load the user list.",
        usersPageStatus: "Page {page} of {total} ({count} users)",
        prev: "← Previous",
        next: "Next →",
        colEmail: "Email",
        colRole: "Role",
        colAge: "Age",
        colGender: "Gender",
        colStars: "Stars",
        colCreated: "Created",
        // topics
        topicsTitle: "Topic Management",
        topicsHint: "A new topic is created as a draft and is not shown to students until published. A topic cannot be published without a published subject.",
        newTopic: "New topic",
        editTopic: "Edit topic",
        topicsLoadError: "Failed to load topics.",
        colStatus: "Status",
        colSubjects: "Subjects",
        colActions: "Actions",
        statusActive: "Active",
        statusDraft: "Draft",
        publish: "Publish",
        disable: "Disable",
        cannotPublishEmpty: "A topic cannot be published without a published subject.",
        topicNamePlaceholder: "Topic name",
        errDuplicateName: "Topic name already exists.",
        errNameRequired: "Topic name is required.",
        manageSubjects: "Manage Subjects",
        // subjects
        subjectsTitle: "Subject Management",
        subjectsOf: "Subjects of {topic}",
        subjectsHint: "A new subject is created as a draft and is not shown to students until published. A subject cannot be published without sub-subjects.",
        newSubject: "New subject",
        editSubject: "Edit subject",
        subjectNamePlaceholder: "Subject name",
        subjectsLoadError: "Failed to load subjects.",
        colSubSubjects: "Sub-subjects",
        backToTopics: "← Back to topics",
        protectedSubject: "Protected subject — cannot be renamed or disabled.",
        protectedSubjectNote: "Protected system subject — cannot be edited or disabled.",
        lastActiveSubject: "Cannot disable the last published subject of an active topic.",
        cannotPublishSubjectEmpty: "A subject cannot be published without a published sub-subject.",
        errSubjectDuplicate: "Subject name already exists.",
        errSubjectRequired: "Subject name is required.",
        manageSubSubjects: "Manage sub-subjects",
        // sub-subjects
        subSubjectsOf: "Sub-subjects of {subject}",
        subSubjectsHint: "A new sub-subject is created as a draft and is not shown to students until published. A sub-subject cannot be published without question templates.",
        newSubSubject: "New sub-subject",
        editSubSubject: "Edit sub-subject",
        subSubjectNamePlaceholder: "Sub-subject name",
        subSubjectsLoadError: "Failed to load sub-subjects.",
        colTemplates: "Question templates",
        backToSubjects: "← Back to subjects",
        protectedSubSubjectNote: "Protected system sub-subject — cannot be edited or disabled.",
        protectedSubjectNoAdd: "This is a protected system subject — sub-subjects cannot be added to it.",
        lastActiveSubSubject: "Cannot disable the last published sub-subject of an active subject.",
        cannotPublishNoTemplates: "A sub-subject without question templates cannot be published.",
        errSubSubjectRequired: "Sub-subject name is required.",
    },
    he: {
        // shared
        loading: "טוען...",
        save: "שמירה",
        cancel: "ביטול",
        edit: "עריכה",
        colId: "ID",
        colName: "שם",
        errGeneric: "הפעולה נכשלה.",
        // dashboard
        dashboardTitle: "לוח ניהול",
        welcome: "ברוך הבא",
        roleLabel: "תפקיד",
        dashboardNote: "שלב 0 — אימות כניסה. מודולי הניהול ייבנו בשלבים הבאים.",
        manageUsers: "ניהול משתמשים →",
        manageTopics: "ניהול נושאים →",
        // analytics
        cardUsers: "משתמשים",
        cardStudents: "תלמידים",
        cardAttempts: "תרגולים",
        cardSuccessRate: "אחוז הצלחה",
        cardActive7d: "לומדים פעילים (7 ימים)",
        hardestTitle: "תתי־נושאים קשים",
        commonErrorsTitle: "טעויות נפוצות",
        leaderboardTitle: "10 המובילים",
        colAttempts: "ניסיונות",
        colSuccessRate: "אחוז הצלחה",
        colError: "סוג טעות",
        colOccurrences: "מספר הופעות",
        analyticsLoadError: "לא הצלחתי לטעון את הנתונים.",
        noData: "אין עדיין נתונים.",
        // users
        usersTitle: "ניהול משתמשים",
        usersLoadError: "לא הצלחתי לטעון את רשימת המשתמשים.",
        usersPageStatus: "עמוד {page} מתוך {total} ({count} משתמשים)",
        prev: "← הקודם",
        next: "הבא →",
        colEmail: "Email",
        colRole: "תפקיד",
        colAge: "גיל",
        colGender: "מגדר",
        colStars: "כוכבים",
        colCreated: "נוצר",
        // topics
        topicsTitle: "ניהול נושאים",
        topicsHint: "נושא חדש נוצר כטיוטה ואינו מוצג לתלמידים עד שמפרסמים אותו. אי אפשר לפרסם נושא בלי תחום לימוד מפורסם.",
        newTopic: "נושא חדש",
        editTopic: "עריכת נושא",
        topicsLoadError: "לא הצלחתי לטעון את הנושאים.",
        colStatus: "סטטוס",
        colSubjects: "תחומי לימוד",
        colActions: "פעולות",
        statusActive: "פעיל",
        statusDraft: "טיוטה",
        publish: "פרסם",
        disable: "השבת",
        cannotPublishEmpty: "אי אפשר לפרסם נושא בלי תחום לימוד מפורסם.",
        topicNamePlaceholder: "שם הנושא",
        errDuplicateName: "שם הנושא כבר קיים.",
        errNameRequired: "שם הנושא נדרש.",
        manageSubjects: "ניהול תחומי לימוד",
        // subjects
        subjectsTitle: "ניהול תחומי לימוד",
        subjectsOf: "תחומי לימוד של {topic}",
        subjectsHint: "תחום לימוד חדש נוצר כטיוטה ולא יוצג לתלמידים עד שמפרסמים אותו. אי אפשר לפרסם תחום לימוד בלי תתי־נושאים.",
        newSubject: "תחום לימוד חדש",
        editSubject: "עריכת תחום לימוד",
        subjectNamePlaceholder: "שם תחום הלימוד",
        subjectsLoadError: "לא הצלחתי לטעון את תחומי הלימוד.",
        colSubSubjects: "תתי-נושאים",
        backToTopics: "← חזרה לנושאים",
        protectedSubject: "תחום לימוד מוגן — אי אפשר לשנות שם או להשבית.",
        protectedSubjectNote: "תחום לימוד מערכת מוגן — אי אפשר לערוך או להשבית",
        lastActiveSubject: "אי אפשר להשבית את תחום הלימוד המפורסם האחרון של נושא פעיל.",
        cannotPublishSubjectEmpty: "אי אפשר לפרסם תחום לימוד בלי תת־נושא מפורסם.",
        errSubjectDuplicate: "שם תחום הלימוד כבר קיים.",
        errSubjectRequired: "שם תחום הלימוד נדרש.",
        manageSubSubjects: "ניהול תתי־נושאים",
        // sub-subjects
        subSubjectsOf: "תתי־נושאים של {subject}",
        subSubjectsHint: "תת־נושא חדש נוצר כטיוטה ולא יוצג לתלמידים עד שמפרסמים אותו. אי אפשר לפרסם תת־נושא בלי תבניות שאלות.",
        newSubSubject: "תת־נושא חדש",
        editSubSubject: "עריכת תת־נושא",
        subSubjectNamePlaceholder: "שם תת־הנושא",
        subSubjectsLoadError: "לא הצלחתי לטעון את תתי־הנושאים.",
        colTemplates: "תבניות שאלות",
        backToSubjects: "← חזרה לתחומי לימוד",
        protectedSubSubjectNote: "תת־נושא מערכת מוגן — אי אפשר לערוך או להשבית.",
        protectedSubjectNoAdd: "זהו תחום לימוד מערכת מוגן — אי אפשר להוסיף אליו תתי־נושאים.",
        lastActiveSubSubject: "אי אפשר להשבית את תת־הנושא המפורסם האחרון של תחום לימוד פעיל.",
        cannotPublishNoTemplates: "אי אפשר לפרסם תת־נושא בלי תבניות שאלות.",
        errSubSubjectRequired: "שם תת־הנושא נדרש.",
    },
    ru: {
        // shared
        loading: "Загрузка...",
        save: "Сохранить",
        cancel: "Отмена",
        edit: "Редактировать",
        colId: "ID",
        colName: "Название",
        errGeneric: "Действие не удалось.",
        // dashboard
        dashboardTitle: "Панель администратора",
        welcome: "Добро пожаловать",
        roleLabel: "роль",
        dashboardNote: "Этап 0 — проверка входа. Модули управления будут добавлены позже.",
        manageUsers: "Управление пользователями →",
        manageTopics: "Управление темами →",
        // analytics
        cardUsers: "Пользователи",
        cardStudents: "Ученики",
        cardAttempts: "Попытки",
        cardSuccessRate: "Процент успеха",
        cardActive7d: "Активные ученики (7 дн.)",
        hardestTitle: "Сложные подтемы",
        commonErrorsTitle: "Частые ошибки",
        leaderboardTitle: "Топ-10 учеников",
        colAttempts: "Попытки",
        colSuccessRate: "Процент успеха",
        colError: "Тип ошибки",
        colOccurrences: "Количество",
        analyticsLoadError: "Не удалось загрузить аналитику.",
        noData: "Пока нет данных.",
        // users
        usersTitle: "Управление пользователями",
        usersLoadError: "Не удалось загрузить список пользователей.",
        usersPageStatus: "Страница {page} из {total} ({count} пользователей)",
        prev: "← Назад",
        next: "Вперёд →",
        colEmail: "Эл. почта",
        colRole: "Роль",
        colAge: "Возраст",
        colGender: "Пол",
        colStars: "Звёзды",
        colCreated: "Создан",
        // topics
        topicsTitle: "Управление темами",
        topicsHint: "Новая тема создаётся как черновик и не показывается ученикам до публикации. Тему нельзя опубликовать без опубликованного subject.",
        newTopic: "Новая тема",
        editTopic: "Редактировать тему",
        topicsLoadError: "Не удалось загрузить темы.",
        colStatus: "Статус",
        colSubjects: "Подтемы",
        colActions: "Действия",
        statusActive: "Активна",
        statusDraft: "Черновик",
        publish: "Опубликовать",
        disable: "Отключить",
        cannotPublishEmpty: "Тему нельзя опубликовать без опубликованного subject.",
        topicNamePlaceholder: "Название темы",
        errDuplicateName: "Тема с таким названием уже существует.",
        errNameRequired: "Название темы обязательно.",
        manageSubjects: "Управление Subjects",
        // subjects
        subjectsTitle: "Управление Subjects",
        subjectsOf: "Subjects темы {topic}",
        subjectsHint: "Новый subject создаётся как черновик и не показывается ученикам до публикации. subject нельзя опубликовать без подтем.",
        newSubject: "Новый subject",
        editSubject: "Редактировать subject",
        subjectNamePlaceholder: "Название subject",
        subjectsLoadError: "Не удалось загрузить subjects.",
        colSubSubjects: "Подтемы",
        backToTopics: "← Назад к темам",
        protectedSubject: "Защищённый subject — нельзя переименовать или отключить.",
        protectedSubjectNote: "Защищённый системный subject — нельзя редактировать или отключить.",
        lastActiveSubject: "Нельзя отключить последний опубликованный subject активной темы.",
        cannotPublishSubjectEmpty: "subject нельзя опубликовать без опубликованной подтемы.",
        errSubjectDuplicate: "subject с таким названием уже существует.",
        errSubjectRequired: "Название subject обязательно.",
        manageSubSubjects: "Управление подтемами",
        // sub-subjects
        subSubjectsOf: "Подтемы: {subject}",
        subSubjectsHint: "Новая подтема создаётся как черновик и не показывается ученикам до публикации. Подтему нельзя опубликовать без шаблонов вопросов.",
        newSubSubject: "Новая подтема",
        editSubSubject: "Редактировать подтему",
        subSubjectNamePlaceholder: "Название подтемы",
        subSubjectsLoadError: "Не удалось загрузить подтемы.",
        colTemplates: "Шаблоны вопросов",
        backToSubjects: "← Назад к subjects",
        protectedSubSubjectNote: "Защищённая системная подтема — нельзя редактировать или отключить.",
        protectedSubjectNoAdd: "Это защищённый системный subject — нельзя добавлять в него подтемы.",
        lastActiveSubSubject: "Нельзя отключить последнюю опубликованную подтему активного subject.",
        cannotPublishNoTemplates: "Подтему без шаблонов вопросов нельзя опубликовать.",
        errSubSubjectRequired: "Название подтемы обязательно.",
    },
};

export const getAdminStrings = (language) => getStrings(ADMIN_STRINGS, language);
