import { getStrings } from "../../i18n/languages.js";

// All Admin UI strings, keyed by ISO language code. English is the fallback base
// (see getStrings). Adding a language = adding one block here.
export const ADMIN_STRINGS = {
    en: {
        // shared
        loading: "Loading...",
        save: "Save",
        cancel: "Cancel",
        edit: "Edit",
        colId: "ID",
        colName: "Name",
        errGeneric: "The action failed.",
        // dashboard
        dashboardTitle: "Admin Dashboard",
        welcome: "Welcome",
        roleLabel: "role",
        dashboardNote: "Phase 0 — entry verification. Management modules will be built in later phases.",
        manageUsers: "Manage users →",
        manageTopics: "Manage topics →",
        // analytics
        cardUsers: "Users",
        cardStudents: "Students",
        cardAttempts: "Attempts",
        cardSuccessRate: "Success rate",
        cardActive7d: "Active learners (7d)",
        hardestTitle: "Learning areas needing attention",
        commonErrorsTitle: "Common errors",
        leaderboardTitle: "Top 10 students",
        colAttempts: "Attempts",
        colSuccessRate: "Success rate",
        colError: "Error pattern",
        colOccurrences: "Occurrences",
        analyticsLoadError: "Failed to load analytics.",
        noData: "No data yet.",
        // ml groups
        mlGroupsTitle: "ML Cluster Groups",
        manageClusters: "ML cluster groups →",
        colClusterId: "Cluster",
        colLabel: "Label",
        colMembers: "Students",
        colAvgAccuracy: "Avg accuracy",
        colTopErrors: "Top errors",
        colModelK: "k",
        colLastRun: "Last run",
        mlTotalAssigned: "{count} students assigned",
        mlGroupsLoadError: "Failed to load cluster groups.",
        mlNoGroups: "No clusters yet. Run clustering to generate groups.",
        runClustering: "Run clustering",
        runningClustering: "Running clustering…",
        runClusteringConfirm: "This will re-run clustering and update the student groups. Continue?",
        clusteringRunSuccess: "Clustering ran successfully. The groups were updated.",
        clusteringRunError: "Cannot run clustering right now. Make sure the clustering microservice is running.",
        // users
        usersTitle: "User Management",
        usersLoadError: "Failed to load the user list.",
        searchPlaceholder: "Search by name, email or ID",
        filterRole: "Role",
        filterAll: "All",
        filterStudents: "Students",
        filterAdmins: "Admins",
        noResults: "No matching users.",
        makeAdmin: "Make admin",
        makeStudent: "Make student",
        changeRoleConfirm: "Change this user's role?",
        roleChangeSuccess: "The user's role was updated.",
        roleChangeBlocked: "This role change is not allowed (you can't change your own role, and the last admin can't be demoted).",
        roleChangeError: "Could not change the role. Please try again.",
        cannotChangeOwnRole: "You can't change your own role.",
        currentAccount: "Your account",
        block: "Block",
        unblock: "Unblock",
        blockConfirm: "Block this user? They won't be able to log in or use the system.",
        unblockConfirm: "Unblock this user?",
        statusChangeSuccess: "The user's status was updated.",
        statusChangeBlocked: "This action is not allowed (you can't block or delete yourself, and the last active admin can't be deactivated).",
        statusChangeError: "Could not change the status. Please try again.",
        userStatusActive: "Active",
        userStatusBlocked: "Blocked",
        userStatusDeleted: "Deactivated",
        softDelete: "Deactivate",
        restore: "Restore",
        softDeleteConfirm: "This will deactivate the user and prevent them from logging in. Historical data is kept. Continue?",
        filterStatus: "Status",
        statusOptDefault: "Active + Blocked",
        statusOptActive: "Active",
        statusOptBlocked: "Blocked",
        statusOptDeleted: "Deactivated",
        statusOptAll: "All",
        editUser: "Edit",
        editUserTitle: "Edit user",
        genderMale: "Male",
        genderFemale: "Female",
        userUpdateSuccess: "The user's details were updated.",
        emailInUse: "That email is already used by another user.",
        invalidDetails: "Invalid details. Check the name (English), email, age and gender.",
        userUpdateError: "Could not update the details. Please try again.",
        usersPageStatus: "Page {page} of {total} ({count} users)",
        prev: "← Previous",
        next: "Next →",
        colEmail: "Email",
        colRole: "Role",
        colAge: "Age",
        colGender: "Gender",
        colStars: "Stars",
        colCreated: "Created",
        // topics
        topicsTitle: "Topic Management",
        topicsHint: "A new topic is created as a draft and is not shown to students until published. A topic cannot be published without a published subject.",
        newTopic: "New topic",
        editTopic: "Edit topic",
        topicsLoadError: "Failed to load topics.",
        colStatus: "Status",
        colSubjects: "Subjects",
        colActions: "Actions",
        statusActive: "Active",
        statusDraft: "Draft",
        publish: "Publish",
        disable: "Disable",
        cannotPublishEmpty: "A topic cannot be published without a published subject.",
        topicNamePlaceholder: "Topic name",
        errDuplicateName: "Topic name already exists.",
        errNameRequired: "Topic name is required.",
        manageSubjects: "Manage Subjects",
        // subjects
        subjectsTitle: "Subject Management",
        subjectsOf: "Subjects of {topic}",
        subjectsHint: "A new subject is created as a draft and is not shown to students until published. A subject cannot be published without sub-subjects.",
        newSubject: "New subject",
        editSubject: "Edit subject",
        subjectNamePlaceholder: "Subject name",
        subjectsLoadError: "Failed to load subjects.",
        colSubSubjects: "Sub-subjects",
        backToTopics: "← Back to topics",
        protectedSubject: "Protected subject — cannot be renamed or disabled.",
        protectedSubjectNote: "Protected system subject — cannot be edited or disabled.",
        lastActiveSubject: "Cannot disable the last published subject of an active topic.",
        cannotPublishSubjectEmpty: "A subject cannot be published without a published sub-subject.",
        errSubjectDuplicate: "Subject name already exists.",
        errSubjectRequired: "Subject name is required.",
        manageSubSubjects: "Manage sub-subjects",
        // sub-subjects
        subSubjectsOf: "Sub-subjects of {subject}",
        subSubjectsHint: "A new sub-subject is created as a draft and is not shown to students until published. A sub-subject cannot be published without question templates.",
        newSubSubject: "New sub-subject",
        editSubSubject: "Edit sub-subject",
        subSubjectNamePlaceholder: "Sub-subject name",
        subSubjectsLoadError: "Failed to load sub-subjects.",
        colTemplates: "Question templates",
        backToSubjects: "← Back to subjects",
        protectedSubSubjectNote: "Protected system sub-subject — cannot be edited or disabled.",
        protectedSubjectNoAdd: "This is a protected system subject — sub-subjects cannot be added to it.",
        lastActiveSubSubject: "Cannot disable the last published sub-subject of an active subject.",
        cannotPublishNoTemplates: "A sub-subject without question templates cannot be published.",
        errSubSubjectRequired: "Sub-subject name is required.",
    },
    he: {
        // shared
        loading: "טוען...",
        save: "שמירה",
        cancel: "ביטול",
        edit: "עריכה",
        colId: "ID",
        colName: "שם",
        errGeneric: "הפעולה נכשלה.",
        // dashboard
        dashboardTitle: "לוח ניהול",
        welcome: "ברוך הבא",
        roleLabel: "תפקיד",
        dashboardNote: "שלב 0 — אימות כניסה. מודולי הניהול ייבנו בשלבים הבאים.",
        manageUsers: "ניהול משתמשים →",
        manageTopics: "ניהול נושאים →",
        // analytics
        cardUsers: "משתמשים",
        cardStudents: "תלמידים",
        cardAttempts: "תרגולים",
        cardSuccessRate: "אחוז הצלחה",
        cardActive7d: "לומדים פעילים (7 ימים)",
        hardestTitle: "תתי־נושאים קשים",
        commonErrorsTitle: "טעויות נפוצות",
        leaderboardTitle: "10 המובילים",
        colAttempts: "ניסיונות",
        colSuccessRate: "אחוז הצלחה",
        colError: "סוג טעות",
        colOccurrences: "מספר הופעות",
        analyticsLoadError: "לא הצלחתי לטעון את הנתונים.",
        noData: "אין עדיין נתונים.",
        // ml groups
        mlGroupsTitle: "קבוצות ML",
        manageClusters: "קבוצות ML →",
        colClusterId: "קבוצה",
        colLabel: "תווית",
        colMembers: "תלמידים",
        colAvgAccuracy: "דיוק ממוצע",
        colTopErrors: "טעויות מובילות",
        colModelK: "k",
        colLastRun: "ריצה אחרונה",
        mlTotalAssigned: "{count} תלמידים משויכים",
        mlGroupsLoadError: "לא הצלחתי לטעון את קבוצות ה‑ML.",
        mlNoGroups: "אין עדיין קבוצות. יש להריץ clustering כדי לייצר קבוצות.",
        runClustering: "הרץ clustering",
        runningClustering: "מריץ clustering…",
        runClusteringConfirm: "פעולה זו תריץ clustering מחדש ותעדכן את קבוצות התלמידים. להמשיך?",
        clusteringRunSuccess: "ה‑clustering הורץ בהצלחה. הקבוצות עודכנו.",
        clusteringRunError: "לא ניתן להריץ clustering כרגע. ודאי שמיקרו־סרוויס הקבוצות רץ.",
        // users
        usersTitle: "ניהול משתמשים",
        usersLoadError: "לא הצלחתי לטעון את רשימת המשתמשים.",
        searchPlaceholder: "חיפוש לפי שם, אימייל או מזהה",
        filterRole: "תפקיד",
        filterAll: "הכול",
        filterStudents: "תלמידים",
        filterAdmins: "מנהלים",
        noResults: "לא נמצאו משתמשים מתאימים.",
        makeAdmin: "הפוך למנהל",
        makeStudent: "הפוך לתלמיד",
        changeRoleConfirm: "לשנות את ה‑role של המשתמש הזה?",
        roleChangeSuccess: "ה‑role של המשתמש עודכן.",
        roleChangeBlocked: "שינוי ה‑role אינו מותר (אי אפשר לשנות את ה‑role של עצמך, ואי אפשר להוריד את האדמין האחרון).",
        roleChangeError: "לא ניתן לשנות את ה‑role. נסי שוב.",
        cannotChangeOwnRole: "אי אפשר לשנות את ה‑role של עצמך.",
        currentAccount: "החשבון שלך",
        block: "חסום",
        unblock: "שחרר",
        blockConfirm: "לחסום את המשתמש הזה? הוא לא יוכל להתחבר או להשתמש במערכת.",
        unblockConfirm: "לשחרר את המשתמש הזה?",
        statusChangeSuccess: "סטטוס המשתמש עודכן.",
        statusChangeBlocked: "הפעולה אינה מותרת (אי אפשר לחסום/להשבית את עצמך, ואי אפשר להשבית את האדמין הפעיל האחרון).",
        statusChangeError: "לא ניתן לשנות את הסטטוס. נסי שוב.",
        userStatusActive: "פעיל",
        userStatusBlocked: "חסום",
        userStatusDeleted: "מושבת",
        softDelete: "השבת",
        restore: "שחזר",
        softDeleteConfirm: "פעולה זו תשבית את המשתמש ותמנע ממנו להתחבר. הנתונים ההיסטוריים יישמרו. להמשיך?",
        filterStatus: "סטטוס",
        statusOptDefault: "פעילים + חסומים",
        statusOptActive: "פעילים",
        statusOptBlocked: "חסומים",
        statusOptDeleted: "מושבתים",
        statusOptAll: "הכול",
        editUser: "ערוך",
        editUserTitle: "עריכת משתמש",
        genderMale: "זכר",
        genderFemale: "נקבה",
        userUpdateSuccess: "פרטי המשתמש עודכנו.",
        emailInUse: "האימייל כבר בשימוש על ידי משתמש אחר.",
        invalidDetails: "פרטים לא תקינים. בדקי שם (אנגלית), אימייל, גיל ומגדר.",
        userUpdateError: "לא ניתן לעדכן את הפרטים. נסי שוב.",
        usersPageStatus: "עמוד {page} מתוך {total} ({count} משתמשים)",
        prev: "← הקודם",
        next: "הבא →",
        colEmail: "Email",
        colRole: "תפקיד",
        colAge: "גיל",
        colGender: "מגדר",
        colStars: "כוכבים",
        colCreated: "נוצר",
        // topics
        topicsTitle: "ניהול נושאים",
        topicsHint: "נושא חדש נוצר כטיוטה ואינו מוצג לתלמידים עד שמפרסמים אותו. אי אפשר לפרסם נושא בלי תחום לימוד מפורסם.",
        newTopic: "נושא חדש",
        editTopic: "עריכת נושא",
        topicsLoadError: "לא הצלחתי לטעון את הנושאים.",
        colStatus: "סטטוס",
        colSubjects: "תחומי לימוד",
        colActions: "פעולות",
        statusActive: "פעיל",
        statusDraft: "טיוטה",
        publish: "פרסם",
        disable: "השבת",
        cannotPublishEmpty: "אי אפשר לפרסם נושא בלי תחום לימוד מפורסם.",
        topicNamePlaceholder: "שם הנושא",
        errDuplicateName: "שם הנושא כבר קיים.",
        errNameRequired: "שם הנושא נדרש.",
        manageSubjects: "ניהול תחומי לימוד",
        // subjects
        subjectsTitle: "ניהול תחומי לימוד",
        subjectsOf: "תחומי לימוד של {topic}",
        subjectsHint: "תחום לימוד חדש נוצר כטיוטה ולא יוצג לתלמידים עד שמפרסמים אותו. אי אפשר לפרסם תחום לימוד בלי תתי־נושאים.",
        newSubject: "תחום לימוד חדש",
        editSubject: "עריכת תחום לימוד",
        subjectNamePlaceholder: "שם תחום הלימוד",
        subjectsLoadError: "לא הצלחתי לטעון את תחומי הלימוד.",
        colSubSubjects: "תתי-נושאים",
        backToTopics: "← חזרה לנושאים",
        protectedSubject: "תחום לימוד מוגן — אי אפשר לשנות שם או להשבית.",
        protectedSubjectNote: "תחום לימוד מערכת מוגן — אי אפשר לערוך או להשבית",
        lastActiveSubject: "אי אפשר להשבית את תחום הלימוד המפורסם האחרון של נושא פעיל.",
        cannotPublishSubjectEmpty: "אי אפשר לפרסם תחום לימוד בלי תת־נושא מפורסם.",
        errSubjectDuplicate: "שם תחום הלימוד כבר קיים.",
        errSubjectRequired: "שם תחום הלימוד נדרש.",
        manageSubSubjects: "ניהול תתי־נושאים",
        // sub-subjects
        subSubjectsOf: "תתי־נושאים של {subject}",
        subSubjectsHint: "תת־נושא חדש נוצר כטיוטה ולא יוצג לתלמידים עד שמפרסמים אותו. אי אפשר לפרסם תת־נושא בלי תבניות שאלות.",
        newSubSubject: "תת־נושא חדש",
        editSubSubject: "עריכת תת־נושא",
        subSubjectNamePlaceholder: "שם תת־הנושא",
        subSubjectsLoadError: "לא הצלחתי לטעון את תתי־הנושאים.",
        colTemplates: "תבניות שאלות",
        backToSubjects: "← חזרה לתחומי לימוד",
        protectedSubSubjectNote: "תת־נושא מערכת מוגן — אי אפשר לערוך או להשבית.",
        protectedSubjectNoAdd: "זהו תחום לימוד מערכת מוגן — אי אפשר להוסיף אליו תתי־נושאים.",
        lastActiveSubSubject: "אי אפשר להשבית את תת־הנושא המפורסם האחרון של תחום לימוד פעיל.",
        cannotPublishNoTemplates: "אי אפשר לפרסם תת־נושא בלי תבניות שאלות.",
        errSubSubjectRequired: "שם תת־הנושא נדרש.",
    },
    ru: {
        // shared
        loading: "Загрузка...",
        save: "Сохранить",
        cancel: "Отмена",
        edit: "Редактировать",
        colId: "ID",
        colName: "Название",
        errGeneric: "Действие не удалось.",
        // dashboard
        dashboardTitle: "Панель администратора",
        welcome: "Добро пожаловать",
        roleLabel: "роль",
        dashboardNote: "Этап 0 — проверка входа. Модули управления будут добавлены позже.",
        manageUsers: "Управление пользователями →",
        manageTopics: "Управление темами →",
        // analytics
        cardUsers: "Пользователи",
        cardStudents: "Ученики",
        cardAttempts: "Попытки",
        cardSuccessRate: "Процент успеха",
        cardActive7d: "Активные ученики (7 дн.)",
        hardestTitle: "Сложные подтемы",
        commonErrorsTitle: "Частые ошибки",
        leaderboardTitle: "Топ-10 учеников",
        colAttempts: "Попытки",
        colSuccessRate: "Процент успеха",
        colError: "Тип ошибки",
        colOccurrences: "Количество",
        analyticsLoadError: "Не удалось загрузить аналитику.",
        noData: "Пока нет данных.",
        // ml groups
        mlGroupsTitle: "ML-группы",
        manageClusters: "ML-группы →",
        colClusterId: "Группа",
        colLabel: "Метка",
        colMembers: "Ученики",
        colAvgAccuracy: "Средняя точность",
        colTopErrors: "Частые ошибки",
        colModelK: "k",
        colLastRun: "Последний запуск",
        mlTotalAssigned: "Назначено учеников: {count}",
        mlGroupsLoadError: "Не удалось загрузить ML-группы.",
        mlNoGroups: "Групп пока нет. Запустите кластеризацию.",
        runClustering: "Запустить кластеризацию",
        runningClustering: "Выполняется кластеризация…",
        runClusteringConfirm: "Это перезапустит кластеризацию и обновит группы учеников. Продолжить?",
        clusteringRunSuccess: "Кластеризация выполнена успешно. Группы обновлены.",
        clusteringRunError: "Сейчас нельзя запустить кластеризацию. Убедитесь, что микросервис кластеризации запущен.",
        // users
        usersTitle: "Управление пользователями",
        usersLoadError: "Не удалось загрузить список пользователей.",
        searchPlaceholder: "Поиск по имени, эл. почте или ID",
        filterRole: "Роль",
        filterAll: "Все",
        filterStudents: "Ученики",
        filterAdmins: "Администраторы",
        noResults: "Подходящие пользователи не найдены.",
        makeAdmin: "Назначить админом",
        makeStudent: "Сделать учеником",
        changeRoleConfirm: "Изменить роль этого пользователя?",
        roleChangeSuccess: "Роль пользователя обновлена.",
        roleChangeBlocked: "Это изменение роли запрещено (нельзя менять свою роль и понижать последнего администратора).",
        roleChangeError: "Не удалось изменить роль. Попробуйте ещё раз.",
        cannotChangeOwnRole: "Нельзя изменить собственную роль.",
        currentAccount: "Ваш аккаунт",
        block: "Заблокировать",
        unblock: "Разблокировать",
        blockConfirm: "Заблокировать этого пользователя? Он не сможет войти или пользоваться системой.",
        unblockConfirm: "Разблокировать этого пользователя?",
        statusChangeSuccess: "Статус пользователя обновлён.",
        statusChangeBlocked: "Действие запрещено (нельзя заблокировать/деактивировать себя и последнего активного администратора).",
        statusChangeError: "Не удалось изменить статус. Попробуйте ещё раз.",
        userStatusActive: "Активен",
        userStatusBlocked: "Заблокирован",
        userStatusDeleted: "Деактивирован",
        softDelete: "Деактивировать",
        restore: "Восстановить",
        softDeleteConfirm: "Пользователь будет деактивирован и не сможет войти. Исторические данные сохранятся. Продолжить?",
        filterStatus: "Статус",
        statusOptDefault: "Активные + заблокированные",
        statusOptActive: "Активные",
        statusOptBlocked: "Заблокированные",
        statusOptDeleted: "Деактивированные",
        statusOptAll: "Все",
        editUser: "Редактировать",
        editUserTitle: "Редактировать пользователя",
        genderMale: "Мужской",
        genderFemale: "Женский",
        userUpdateSuccess: "Данные пользователя обновлены.",
        emailInUse: "Эта эл. почта уже используется другим пользователем.",
        invalidDetails: "Неверные данные. Проверьте имя (англ.), эл. почту, возраст и пол.",
        userUpdateError: "Не удалось обновить данные. Попробуйте ещё раз.",
        usersPageStatus: "Страница {page} из {total} ({count} пользователей)",
        prev: "← Назад",
        next: "Вперёд →",
        colEmail: "Эл. почта",
        colRole: "Роль",
        colAge: "Возраст",
        colGender: "Пол",
        colStars: "Звёзды",
        colCreated: "Создан",
        // topics
        topicsTitle: "Управление темами",
        topicsHint: "Новая тема создаётся как черновик и не показывается ученикам до публикации. Тему нельзя опубликовать без опубликованного subject.",
        newTopic: "Новая тема",
        editTopic: "Редактировать тему",
        topicsLoadError: "Не удалось загрузить темы.",
        colStatus: "Статус",
        colSubjects: "Подтемы",
        colActions: "Действия",
        statusActive: "Активна",
        statusDraft: "Черновик",
        publish: "Опубликовать",
        disable: "Отключить",
        cannotPublishEmpty: "Тему нельзя опубликовать без опубликованного subject.",
        topicNamePlaceholder: "Название темы",
        errDuplicateName: "Тема с таким названием уже существует.",
        errNameRequired: "Название темы обязательно.",
        manageSubjects: "Управление Subjects",
        // subjects
        subjectsTitle: "Управление Subjects",
        subjectsOf: "Subjects темы {topic}",
        subjectsHint: "Новый subject создаётся как черновик и не показывается ученикам до публикации. subject нельзя опубликовать без подтем.",
        newSubject: "Новый subject",
        editSubject: "Редактировать subject",
        subjectNamePlaceholder: "Название subject",
        subjectsLoadError: "Не удалось загрузить subjects.",
        colSubSubjects: "Подтемы",
        backToTopics: "← Назад к темам",
        protectedSubject: "Защищённый subject — нельзя переименовать или отключить.",
        protectedSubjectNote: "Защищённый системный subject — нельзя редактировать или отключить.",
        lastActiveSubject: "Нельзя отключить последний опубликованный subject активной темы.",
        cannotPublishSubjectEmpty: "subject нельзя опубликовать без опубликованной подтемы.",
        errSubjectDuplicate: "subject с таким названием уже существует.",
        errSubjectRequired: "Название subject обязательно.",
        manageSubSubjects: "Управление подтемами",
        // sub-subjects
        subSubjectsOf: "Подтемы: {subject}",
        subSubjectsHint: "Новая подтема создаётся как черновик и не показывается ученикам до публикации. Подтему нельзя опубликовать без шаблонов вопросов.",
        newSubSubject: "Новая подтема",
        editSubSubject: "Редактировать подтему",
        subSubjectNamePlaceholder: "Название подтемы",
        subSubjectsLoadError: "Не удалось загрузить подтемы.",
        colTemplates: "Шаблоны вопросов",
        backToSubjects: "← Назад к subjects",
        protectedSubSubjectNote: "Защищённая системная подтема — нельзя редактировать или отключить.",
        protectedSubjectNoAdd: "Это защищённый системный subject — нельзя добавлять в него подтемы.",
        lastActiveSubSubject: "Нельзя отключить последнюю опубликованную подтему активного subject.",
        cannotPublishNoTemplates: "Подтему без шаблонов вопросов нельзя опубликовать.",
        errSubSubjectRequired: "Название подтемы обязательно.",
    },
};

export const getAdminStrings = (language) => getStrings(ADMIN_STRINGS, language);
