import { getStrings } from "../../i18n/languages.js";

// Strings for the one-time placement assessment flow (LevelManagerPage →
// SurveyForm → AssessmentQuestion), keyed by ISO code. English is the fallback
// base (see getStrings). Use format() for {grade}, {count}, {answer}, {level}.
export const LEVEL_MANAGER_STRINGS = {
    en: {
        // page header + step indicator
        stepAboutYou: "About You",
        stepAssessment: "Assessment Question",
        pageTitle: "Level Assessment",
        pageSubtitle: "We'll place you at the right level so every question feels just right.",
        // survey form
        surveyHeading: "Tell us about yourself",
        surveySubtext: "We'll use this to place you at exactly the right level.",
        gradeLabel: "What grade are you in?",
        gradePlaceholder: "— Select grade —",
        gradeOption: "Grade {grade}",
        confidenceLabel: "How confident are you in math?",
        confBeginnerTitle: "Beginner",
        confBeginnerDesc: "Math feels hard for me",
        confComfortableTitle: "Comfortable",
        confComfortableDesc: "I know the basics well",
        confAdvancedTitle: "Advanced",
        confAdvancedDesc: "I enjoy hard problems",
        subjectLabel: "Subject:",
        subjectLoading: "Loading subjects...",
        subjectPlaceholder: "— Select subject —",
        chooseTopics: "Choose topics to practice:",
        selectedCount: "{count} selected",
        topicsLoading: "Loading topics...",
        noTopicsForSubject: "No topics found for this subject.",
        startAssessment: "Start Assessment →",
        loading: "Loading...",
        // survey errors
        errNoTopics: "No topics available. Please contact support.",
        errNoSubjects: "No subjects found for this topic. Please contact support.",
        errLoadSubjects: "Could not load subjects. Please refresh the page.",
        errNoSubSubjects: "No sub-subjects found for this subject.",
        errLoadSubSubjects: "Could not load sub-subjects. Please try again.",
        errStartAssessment: "Could not start the assessment. Please try again.",
        // assessment question
        questionHeading: "Assessment Question",
        questionSubtext: "Answer this question so we can set your starting level. There's no wrong outcome — just answer honestly!",
        difficulty: "Difficulty {level}",
        answerPlaceholder: "Type your answer",
        submit: "Submit",
        questionCounter: "Question {current} of {total}",
        backBtn: "Back",
        continueBtn: "Continue",
        noWrongAnswer: "There's no wrong answer — just answer honestly.",
        continueToPractice: "Continue to practice →",
        feedbackCorrect: "Correct! Great start!",
        feedbackWrong: "Not quite — the answer was {answer}. No worries, we've noted your level!",
        errSubmit: "Could not submit your answer. Please try again.",
    },
    he: {
        // page header + step indicator
        stepAboutYou: "עליך",
        stepAssessment: "שאלת הערכה",
        pageTitle: "הערכת רמה",
        pageSubtitle: "נשבץ אתכם ברמה המתאימה כדי שכל שאלה תהיה בדיוק במידה.",
        // survey form
        surveyHeading: "ספרו לנו על עצמכם",
        surveySubtext: "נשתמש בזה כדי לשבץ אתכם בדיוק ברמה הנכונה.",
        gradeLabel: "באיזו כיתה אתם?",
        gradePlaceholder: "— בחרו כיתה —",
        gradeOption: "כיתה {grade}",
        confidenceLabel: "כמה אתם בטוחים במתמטיקה?",
        confBeginnerTitle: "מתחיל/ה",
        confBeginnerDesc: "מתמטיקה קשה לי",
        confComfortableTitle: "בנוח",
        confComfortableDesc: "אני יודע/ת את הבסיס היטב",
        confAdvancedTitle: "מתקדם/ת",
        confAdvancedDesc: "אני נהנה/ית מבעיות קשות",
        subjectLabel: "נושא:",
        subjectLoading: "טוען נושאים...",
        subjectPlaceholder: "— בחרו נושא —",
        chooseTopics: "בחרו נושאים לתרגול:",
        selectedCount: "{count} נבחרו",
        topicsLoading: "טוען נושאים...",
        noTopicsForSubject: "לא נמצאו נושאים עבור נושא זה.",
        startAssessment: "התחל הערכה →",
        loading: "טוען...",
        // survey errors
        errNoTopics: "אין נושאים זמינים. אנא פנו לתמיכה.",
        errNoSubjects: "לא נמצאו נושאים עבור נושא זה. אנא פנו לתמיכה.",
        errLoadSubjects: "לא ניתן לטעון נושאים. אנא רעננו את הדף.",
        errNoSubSubjects: "לא נמצאו תתי-נושאים עבור נושא זה.",
        errLoadSubSubjects: "לא ניתן לטעון תתי-נושאים. אנא נסו שוב.",
        errStartAssessment: "לא ניתן להתחיל את ההערכה. אנא נסו שוב.",
        // assessment question
        questionHeading: "שאלת הערכה",
        questionSubtext: "ענו על השאלה כדי שנוכל לקבוע את רמת הפתיחה שלכם. אין תוצאה שגויה — פשוט ענו בכנות!",
        difficulty: "רמת קושי {level}",
        answerPlaceholder: "הקלידו את תשובתכם",
        submit: "שליחה",
        questionCounter: "שאלה {current} מתוך {total}",
        backBtn: "חזרה",
        continueBtn: "המשך",
        noWrongAnswer: "אין תשובה לא טובה — פשוט ענו בכנות.",
        continueToPractice: "המשך לתרגול →",
        feedbackCorrect: "נכון! התחלה מצוינת!",
        feedbackWrong: "כמעט — התשובה הייתה {answer}. אל דאגה, רשמנו את הרמה שלכם!",
        errSubmit: "לא ניתן לשלוח את תשובתכם. אנא נסו שוב.",
    },
    ru: {
        // page header + step indicator
        stepAboutYou: "О вас",
        stepAssessment: "Оценочный вопрос",
        pageTitle: "Оценка уровня",
        pageSubtitle: "Мы определим ваш уровень, чтобы каждый вопрос был как раз по силам.",
        // survey form
        surveyHeading: "Расскажите о себе",
        surveySubtext: "Мы используем это, чтобы подобрать вам точно подходящий уровень.",
        gradeLabel: "В каком вы классе?",
        gradePlaceholder: "— Выберите класс —",
        gradeOption: "{grade} класс",
        confidenceLabel: "Насколько вы уверены в математике?",
        confBeginnerTitle: "Начинающий",
        confBeginnerDesc: "Математика даётся мне трудно",
        confComfortableTitle: "Уверенно",
        confComfortableDesc: "Я хорошо знаю основы",
        confAdvancedTitle: "Продвинутый",
        confAdvancedDesc: "Мне нравятся сложные задачи",
        subjectLabel: "Предмет:",
        subjectLoading: "Загрузка предметов...",
        subjectPlaceholder: "— Выберите предмет —",
        chooseTopics: "Выберите темы для тренировки:",
        selectedCount: "выбрано: {count}",
        topicsLoading: "Загрузка тем...",
        noTopicsForSubject: "Для этого предмета темы не найдены.",
        startAssessment: "Начать оценку →",
        loading: "Загрузка...",
        // survey errors
        errNoTopics: "Нет доступных тем. Обратитесь в поддержку.",
        errNoSubjects: "Для этой темы предметы не найдены. Обратитесь в поддержку.",
        errLoadSubjects: "Не удалось загрузить предметы. Обновите страницу.",
        errNoSubSubjects: "Для этого предмета подтемы не найдены.",
        errLoadSubSubjects: "Не удалось загрузить подтемы. Попробуйте ещё раз.",
        errStartAssessment: "Не удалось начать оценку. Попробуйте ещё раз.",
        // assessment question
        questionHeading: "Оценочный вопрос",
        questionSubtext: "Ответьте на этот вопрос, чтобы мы определили ваш начальный уровень. Нет неправильного исхода — просто отвечайте честно!",
        difficulty: "Сложность {level}",
        answerPlaceholder: "Введите ваш ответ",
        submit: "Отправить",
        questionCounter: "Вопрос {current} из {total}",
        backBtn: "Назад",
        continueBtn: "Продолжить",
        noWrongAnswer: "Нет неправильного ответа — просто отвечайте честно.",
        continueToPractice: "Перейти к практике →",
        feedbackCorrect: "Верно! Отличное начало!",
        feedbackWrong: "Почти — правильный ответ: {answer}. Не переживайте, мы отметили ваш уровень!",
        errSubmit: "Не удалось отправить ваш ответ. Попробуйте ещё раз.",
    },
};

export const getLevelManagerStrings = (language) => getStrings(LEVEL_MANAGER_STRINGS, language);
