import { getStrings } from "../i18n/languages.js";

// Strings for the Login/Register screens, keyed by ISO language code.
// English is the fallback base (see getStrings).
export const AUTH_STRINGS = {
    en: {
        emailPh: "Enter email",
        passwordPh: "Enter password",
        show: "Show",
        hide: "Hide",
        login: "Login",
        invalidCreds: "Email or Password are incorrect",
        accountBlocked: "Your account is blocked. Please contact the administrator.",
        network: "Server communication error, please try again later",
        noAccount: "Don't have an account?",
        registerHere: "Register here",
        fullNamePh: "Enter full name",
        confirmPh: "Confirm password",
        agePh: "Enter age",
        register: "Register",
        registerFailed: "Registration failed",
        registerOk: "You have registered successfully. Please log in.",
        codePh: "Enter Code",
        send: "Send",
        invalidCode: "Invalid code",
        male: "Male",
        female: "Female",
    },
    he: {
        emailPh: "הכניסו אימייל",
        passwordPh: "הכניסו סיסמה",
        show: "הצג",
        hide: "הסתר",
        login: "התחברות",
        invalidCreds: "אימייל או סיסמה שגויים",
        accountBlocked: "החשבון חסום. פנה למנהל המערכת.",
        network: "שגיאת תקשורת עם השרת, אנא נסו שוב מאוחר יותר",
        noAccount: "אין לך משתמש?",
        registerHere: "הירשם כאן",
        fullNamePh: "הכניסו שם מלא",
        confirmPh: "אימות סיסמה",
        agePh: "הכניסו גיל",
        register: "הרשמה",
        registerFailed: "ההרשמה נכשלה",
        registerOk: "נרשמת בהצלחה. אנא התחבר/י.",
        codePh: "הכניסו קוד",
        send: "שליחה",
        invalidCode: "קוד שגוי",
        male: "זכר",
        female: "נקבה",
    },
    ru: {
        emailPh: "Введите эл. почту",
        passwordPh: "Введите пароль",
        show: "Показать",
        hide: "Скрыть",
        login: "Вход",
        invalidCreds: "Неверная эл. почта или пароль",
        accountBlocked: "Ваш аккаунт заблокирован. Обратитесь к администратору.",
        network: "Ошибка связи с сервером, попробуйте позже",
        noAccount: "Нет аккаунта?",
        registerHere: "Зарегистрируйтесь",
        fullNamePh: "Введите полное имя",
        confirmPh: "Подтвердите пароль",
        agePh: "Введите возраст",
        register: "Регистрация",
        registerFailed: "Регистрация не удалась",
        registerOk: "Регистрация успешна. Войдите в систему.",
        codePh: "Введите код",
        send: "Отправить",
        invalidCode: "Неверный код",
        male: "Мужской",
        female: "Женский",
    },
};

export const getAuthStrings = (language) => getStrings(AUTH_STRINGS, language);
