import { getStrings } from "../../i18n/languages.js";

// Strings for the QuestionGame (the active exercise screen), keyed by ISO code.
// English is the fallback base (see getStrings). Use format() for the {level},
// {current}, {max}, {target}, {count}, {label} placeholders.
//
// NOTE: the server may send its own feedback text (data.message); when present it
// is shown and these strings act only as the fallback.
export const QUESTION_GAME_STRINGS = {
    en: {
        back: "Back",
        practiceFallback: "Practice",
        adaptedForYou: "🎯 Adapted for you",
        adaptedTitle: "Tailored to your learning group: {label}",
        streak: "🔥 {count} Streak!",
        bonusBanner: "🌟 Bonus question — harder, worth 50 stars!",
        difficulty: "Difficulty {level}",
        attempt: "Attempt {current}/{max}",
        answerPlaceholder: "Type your answer",
        submit: "Submit",
        hint: "💡 Hint",
        showSolution: "Show full solution",
        goToBonus: "Go to bonus question →",
        nextQuestion: "Next question →",
        level: "Level {level}",
        subLevel: " · Sub-level (easier practice)",
        toNextLevel: "{current}/{target} to next level",
        levelUpCelebrate: "Great job! You reached the next level",
        subLevelPaused: "Solve a few easier questions to get back to your level — the bar is paused.",
        loading: "Loading...",
        // feedback (fallbacks for the server message)
        correct: "Correct! ✅",
        outOfTries: "Out of tries — here is the solution.",
        tryAgain: "Not quite — try again ({current}/{max}).",
        bonusSolved: "Bonus solved! +50 ⭐",
        bonusMissed: "Bonus missed — no stars this time.",
        solutionShown: "Solution shown — this one is marked as failed.",
        // errors
        errLoadQuestion: "Could not load the question. Please try again.",
        errLoadBonus: "Could not load the bonus question.",
        errSubmit: "Could not submit your answer. Please try again.",
        errSubmitBonus: "Could not submit the bonus answer.",
        errRevealSolution: "Could not reveal the solution.",
    },
    he: {
        back: "חזרה",
        practiceFallback: "תרגול",
        adaptedForYou: "🎯 מותאם עבורך",
        adaptedTitle: "מותאם לקבוצת הלמידה שלך: {label}",
        streak: "🔥 {count} ברצף!",
        bonusBanner: "🌟 שאלת בונוס — קשה יותר, שווה 50 כוכבים!",
        difficulty: "רמת קושי {level}",
        attempt: "ניסיון {current}/{max}",
        answerPlaceholder: "הקלידו את תשובתכם",
        submit: "שליחה",
        hint: "💡 רמז",
        showSolution: "הצג פתרון מלא",
        goToBonus: "לשאלת הבונוס →",
        nextQuestion: "השאלה הבאה →",
        level: "רמה {level}",
        subLevel: " · תת-רמה (תרגול קל יותר)",
        toNextLevel: "{current}/{target} לרמה הבאה",
        levelUpCelebrate: "כל הכבוד! הגעת לרמה הבאה",
        subLevelPaused: "פתרו כמה שאלות קלות יותר כדי לחזור לרמה שלכם — הסרגל מושהה.",
        loading: "טוען...",
        // feedback (fallbacks for the server message)
        correct: "נכון! ✅",
        outOfTries: "נגמרו הניסיונות — הנה הפתרון.",
        tryAgain: "כמעט — נסו שוב ({current}/{max}).",
        bonusSolved: "פתרת את הבונוס! +50 ⭐",
        bonusMissed: "פספסת את הבונוס — אין כוכבים הפעם.",
        solutionShown: "הפתרון הוצג — שאלה זו סומנה כנכשלה.",
        // errors
        errLoadQuestion: "לא ניתן לטעון את השאלה. אנא נסו שוב.",
        errLoadBonus: "לא ניתן לטעון את שאלת הבונוס.",
        errSubmit: "לא ניתן לשלוח את תשובתכם. אנא נסו שוב.",
        errSubmitBonus: "לא ניתן לשלוח את תשובת הבונוס.",
        errRevealSolution: "לא ניתן לחשוף את הפתרון.",
    },
    ru: {
        back: "Назад",
        practiceFallback: "Практика",
        adaptedForYou: "🎯 Адаптировано для вас",
        adaptedTitle: "Подобрано для вашей учебной группы: {label}",
        streak: "🔥 Серия из {count}!",
        bonusBanner: "🌟 Бонусный вопрос — сложнее, стоит 50 звёзд!",
        difficulty: "Сложность {level}",
        attempt: "Попытка {current}/{max}",
        answerPlaceholder: "Введите ваш ответ",
        submit: "Отправить",
        hint: "💡 Подсказка",
        showSolution: "Показать полное решение",
        goToBonus: "К бонусному вопросу →",
        nextQuestion: "Следующий вопрос →",
        level: "Уровень {level}",
        subLevel: " · Подуровень (упрощённая практика)",
        toNextLevel: "{current}/{target} до следующего уровня",
        levelUpCelebrate: "Отлично! Вы достигли следующего уровня",
        subLevelPaused: "Решите несколько более лёгких вопросов, чтобы вернуться на свой уровень — прогресс приостановлен.",
        loading: "Загрузка...",
        // feedback (fallbacks for the server message)
        correct: "Верно! ✅",
        outOfTries: "Попытки закончились — вот решение.",
        tryAgain: "Почти — попробуйте ещё раз ({current}/{max}).",
        bonusSolved: "Бонус решён! +50 ⭐",
        bonusMissed: "Бонус не угадан — в этот раз без звёзд.",
        solutionShown: "Решение показано — этот вопрос отмечен как неудачный.",
        // errors
        errLoadQuestion: "Не удалось загрузить вопрос. Попробуйте ещё раз.",
        errLoadBonus: "Не удалось загрузить бонусный вопрос.",
        errSubmit: "Не удалось отправить ваш ответ. Попробуйте ещё раз.",
        errSubmitBonus: "Не удалось отправить бонусный ответ.",
        errRevealSolution: "Не удалось показать решение.",
    },
};

export const getQuestionGameStrings = (language) => getStrings(QUESTION_GAME_STRINGS, language);
